version: '3'

services:
  gdpr-visualization:
    container_name: gdpr-visualization
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
        - "8077:80"
    expose:
        - "8077"
